### ISSUE TITLE
sudo resource failing under 11.16.2

### ISSUE THREAD

**Issue by chrissnell** [chef-cookbooks/sudo#50]
```
Recipe: r_base::default
  * sudo[rackconnect] action install

    ================================================================================
    Error executing action `install` on resource 'sudo[rackconnect]'
    ================================================================================

    NameError
    ---------
    undefined local variable or method `node' for #<Erubis::Context:0x000000031da508>

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/sudo/providers/default.rb:123:in `capture'
    /var/chef/cache/cookbooks/sudo/providers/default.rb:44:in `validate_fragment!'
    /var/chef/cache/cookbooks/sudo/providers/default.rb:95:in `render_sudoer'
    /var/chef/cache/cookbooks/sudo/providers/default.rb:103:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/r_base/recipes/default.rb

     32: sudo "rackconnect" do
     33:   user "rackconnect"
     34:   nopasswd true
     35:   only_if "test -d /home/rackconnect"
     36: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/r_base/recipes/default.rb:32:in `from_file'

    sudo("rackconnect") do
      action :install
      supports {:report=>true, :exception=>true}
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name "r_base"
      recipe_name "default"
      user "rackconnect"
      nopasswd true
      runas "ALL"
      host "ALL"
      commands ["ALL"]
      only_if "test -d /home/rackconnect"
    end

Running handlers:
[2014-09-16T21:18:35+00:00] ERROR: Running exception handlers
Running handlers complete
[2014-09-16T21:18:35+00:00] ERROR: Exception handlers complete
[2014-09-16T21:18:35+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 8 resources updated in 23.388949252 seconds
[2014-09-16T21:18:36+00:00] ERROR: sudo[rackconnect] (r_base::default line 32) had an error: NameError: undefined local variable or method `node' for #<Erubis::Context:0x000000031da508>
[2014-09-16T21:18:36+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by lbosque** [comment]
I've been struggling with this too. Things changed in Chef 11.6 so if you are having problems with a version previous to this commit:
https://github.com/opscode-cookbooks/sudo/commit/6565c809111740191b1a6d170d39b61b18c04c9c

You have two options: either you update your code with the mentioned commit or if you want to keep node['fqdn'] you can apply a patch like this:
https://github.com/lbosque/sudo/commit/9e2111d4a6b9acf03029830740c4389f2eb31bc5

**Comment by chrissnell** [comment]
@lbosque You reference a commit dating to 2013.  I actually have that commit applied already and I'm still having problems (well...was having problems...I started using cookbook_file as detailed above).

While node['fqdn'] may have caused a problem, I'm not sure if it's the cause of the problem I'm reporting.

**Comment by lbosque** [comment]
Ok, as I commented on the thread I was just covering the case where you had
a older version and the problem was node['fqdn'] in case it helped you.
That was actually my case.

Good luck with that

2015-01-15 18:10 GMT+01:00 Christopher Snell <notifications@github.com>:

**Comment by tas50** [comment]
This should be resolved in the latest cookbook as the fqdn logic is removed. Feel free to open it up if it's still a problem.
