### ISSUE TITLE
Limiting a user's commands causes a validation error

### ISSUE THREAD

**Issue by arlininger** [chef-cookbooks/sudo#73]
In my recipe, I am trying to set up a user `rsnapshot` to be permitted to run rsync with passwordless sudo. I would expect that's what the snippet below should do. However, it fails with a validation error. If I remove the `commands` line, all works fine.

```
sudo "<redacted>" do
  user "rsnapshot"
  nopasswd true
  commands ['rsync']
end
```

When this recipe gets run on a host, I get this error.

```

    ================================================================================
    Error executing action `install` on resource 'sudo[<redacted>]'
    ================================================================================

    SystemExit
    ----------
    exit

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/sudo/providers/default.rb:51:in `validate_fragment!'
    /var/chef/cache/cookbooks/sudo/providers/default.rb:100:in `render_sudoer'
    /var/chef/cache/cookbooks/sudo/providers/default.rb:117:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/<redacted>/recipes/default.rb

     19: sudo "<redacted>" do
     20:   user "rsnapshot"
     21:   nopasswd true
     22:   commands ['rsync']
     23: end
     24:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/<redacted>/recipes/default.rb:19:in `from_file'

    sudo("<redacted>") do
      action :install
      supports {:report=>true, :exception=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :sudo
      cookbook_name "<redacted>"
      recipe_name "default"
      user "rsnapshot"
      nopasswd true
      commands ["rsync"]
      host "ALL"
      runas "ALL"
    end
```

**Comment by nkadel-skyhook** [comment]
Before you go too much further, try specifying:

           commands ["/usr/bin/rsync"]

**Comment by liamdawson** [comment]
I can confirm that `systemctl blah` didn't work in my case, whereas `/bin/systemctl blah` did.

**Comment by oslerw** [comment]
I can also confirm this issue, for me testing with `pacman` doesn't work, but `/usr/bin/pacman` does:

```ruby
  sudo 'makepkg-pacman' do
    user 'makepkg'
    nopasswd true
    commands ['/usr/bin/pacman'] # Working!
    notifies :reload, 'ohai[reload]', :immediately
  end
```

**Comment by majormoses** [comment]
I think we could inspect each element of commands and bail with a more useful error when a command does not start with `/` or `.`.
