### ISSUE TITLE
No such file or directory - visudo

### ISSUE THREAD

**Issue by salsa-dev** [chef-cookbooks/sudo#88]
The problem is when there is no sudo package installed the validator (visudo) fails as it is not installed on the system.
### Cookbook version

"version":"3.0.0"
### Chef-client version

Chef: 12.9.41
### Platform Details

"Debian GNU/Linux 8 (jessie)"
### Scenario:

I'm trying to run cookbook LWRP:

```
node.default['authorization']['sudo']['sudoers_defaults'] = ['env_reset']
node.default['authorization']['sudo']['include_sudoers_d'] = true

sudo 'ops' do
  user      "ops"
  runas     'root'
  nopasswd  true
  commands  ["/usr/local/bin/indexer"]
end
```
### Steps to Reproduce:

Run cookbook on platform without sudo pakcage installed or just purge the sudo package from the operation system.
### Expected Result:

```
Converging 1 resources
Recipe: bkt::sudo
  * sudo[ops] action install
    * template[/etc/sudoers.d/ops] action create
      - update content in file /etc/sudoers.d/ops from c3255c to 021371
      --- /etc/sudoers.d/ops    2016-09-30 10:49:20.543075000 +0300
      +++ /etc/sudoers.d/.chef-ops20160930-7501-1iow7bt 2016-09-30 10:51:04.807075000 +0300
      @@ -1,2 +1,9 @@
      +# This file is managed by Chef.
      +# Do NOT modify this file directly.
      +
      +
      +
      +
       ops ALL=(root) NOPASSWD:/usr/local/bin/indexer
      +
      - change mode from '0644' to '0440'
    * template[/etc/sudoers.d/ops] action nothing (skipped due to action :nothing)


Running handlers:
Running handlers complete
Chef Client finished, 2/3 resources updated in 33 seconds

```
### Actual Result:

```
Converging 1 resources
Recipe: bkt::sudo
  * sudo[ops] action install

    ================================================================================
    Error executing action `install` on resource 'sudo[ops]'
    ================================================================================

    Errno::ENOENT
    -------------
    No such file or directory - visudo

    Cookbook Trace:
    ---------------
    /root/chef/.chef/local-mode-cache/cache/cookbooks/sudo/providers/default.rb:49:in `validate_fragment!'
    /root/chef/.chef/local-mode-cache/cache/cookbooks/sudo/providers/default.rb:104:in `render_sudoer'
    /root/chef/.chef/local-mode-cache/cache/cookbooks/sudo/providers/default.rb:122:in `block in class_from_file'
    /root/chef/.chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

    Resource Declaration:
    ---------------------
    # In /root/chef/.chef/local-mode-cache/cache/cookbooks/bkt/recipes/sudo.rb

     10: sudo 'ops' do
     11:   user      "ops"
     12:   runas     'root'
     13:   nopasswd  true
     14:   commands  ["/usr/local/bin/indexer"]
     15: end

    Compiled Resource:
    ------------------
    # Declared in /root/chef/.chef/local-mode-cache/cache/cookbooks/bkt/recipes/sudo.rb:10:in `from_file'

    sudo("ops") do
      action :install
      supports {:report=>true, :exception=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :sudo
      cookbook_name "bkt"
      recipe_name "sudo"
      user "ops"
      runas "root"
      nopasswd true
      commands ["/usr/local/bin/indexer"]
      host "ALL"
    end

    Platform:
    ---------
    x86_64-linux


Running handlers:
[2016-09-30T10:55:33+03:00] ERROR: Running exception handlers
Running handlers complete
[2016-09-30T10:55:33+03:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 31 seconds
[2016-09-30T10:55:33+03:00] FATAL: Stacktrace dumped to /root/chef/.chef/local-mode-cache/cache/chef-stacktrace.out
[2016-09-30T10:55:33+03:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-09-30T10:55:33+03:00] ERROR: sudo[ops] (bkt::sudo line 10) had an error: Errno::ENOENT: No such file or directory - visudo
[2016-09-30T10:55:35+03:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```

**Comment by shaneramey** [comment]
I had this issue because I was using the 'sudo' provider without having the 'sudo' package installed. I found that Sudo package installation is done in the `sudo::default.rb` recipe, so adding `include_recipe 'sudo'` in your bkt::sudo recipe might do the trick (as it did for me).

**Comment by dpattmann** [comment]
@salsa-dev try to add ```['authorization']['sudo'][''sudoers_defaults] = ['secure_path = /sbin:/bin:/usr/sbin:/usr/bin']``` to your attributes. That solved the problem on RHEL.

**Comment by iennae** [comment]
@dpattmann's solution explains the change in chef 13 which cleaned up some pathing issues (if your issue is with not finding sudo in pathing). 

If your issue is with sudo not getting installed, the latest version 3.5.0 includes installing the package if it's not installed.
